server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost}:${KAFKA_PORT:9092}
    topic:
      teste: teste
    consumer:
      group-id: ${KAFKA_GROUP_ID:orchestrator-group}
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF