server:
  port: 8091

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payment-db}
    platform: postgresql
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
      format-sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost}:${KAFKA_PORT:9092}
    topic:
      orchestrator: orchestrator
      payment-success: payment-success
      payment-fail: payment-fail
    consumer:
      group-id: ${KAFKA_GROUP_ID:payment-group}
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF