server:
  port: 8092

spring:
    kafka:
      bootstrap-servers: ${KAFKA_BROKER:localhost}:${KAFKA_PORT:9092}
      topic:
        orchestrator: orchestrator
        product-validation-success: product-validation-success
        product-validation-fail: product-validation-fail
      consumer:
        group-id: ${KAFKA_GROUP_ID:product-validation-group}
        auto-offset-reset: latest

    datasource:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:inventory-db}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect